# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: afee073b2acd039fc4ad54970b14cd9610f4861b57e9383c4d5ad7a73ce3f590528a6272b302eeae6f052a8a046c62dce184e0c750b35f1f0b02e34a668f1425

test:
  secret_key_base: 8ab026b4ab93e0e359424e1d40e975c85af73e95e95ab4d535f9dc1f8c1a100a8114dce1b53ab876ea5a7bd04e1789d1529141d5f7ac58754df00b698cb4e8c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
